app/message/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from flask_pagedown.fields import PageDownField


class LetterForm(FlaskForm):
    body = PageDownField('评论', validators=[DataRequired()])

app/message/__init__.py
from flask import Blueprint

message = Blueprint('message', __name__)

from . import views

app/message/views.py
from datetime import datetime
from flask import redirect, render_template, current_app, request, g, flash, url_for
from flask_login import login_required, current_user

from ..models import User, Conversation, Post, Permission
from ..user.forms import SearchForm
from .. import db
from . import message
from .forms import LetterForm


# 用户最后一次访问时间,全文搜索
@message.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now()
        db.session.add(current_user)
        db.session.commit()
    g.search_form = SearchForm()

@message.route('/comment')
@login_required
def comment_message():
    user = User.query.filter_by(id=current_user.id).first()
    all_post = user.posts.order_by(Post.timestamp.desc()).all()
    posts = [post for post in all_post if post.draft == False]
    # 每篇文章的评论，赞是一个列表集合
    i = [post.comments for post in posts]
    x, comments = 0, []
    if i != []:
        while x < len(i):
            comments += i[x]
            x += 1
        for comment in comments:
            comment.unread = False
    like_num = [post.like_num for post in posts]
    n, likes = 0, []
    if like_num != []:
        while n < len(like_num):
            likes += like_num[n]
            n += 1
        likes = [like for like in likes if like.unread is True]
    follows = [f for f in user.followers if f.unread is True]

    return render_template('message/comment_message.html',
                           title='消息',
                           like=len(likes),
                           follow=len(follows),
                           comments=comments)

@message.route('/like')
@login_required
def like_message():
    user = User.query.filter_by(id=current_user.id).first()
    all_post = user.posts.order_by(Post.timestamp.desc()).all()
    posts = [post for post in all_post if post.draft == False]

    i = [post.comments for post in posts]
    x, comments = 0, []
    if i != []:
        while x < len(i):
            comments += i[x]
            x += 1
        comments = [comment for comment in comments if comment.unread is True]
    like_num = [post.like_num for post in posts]
    n, likes = 0, []
    if like_num != []:
        while n < len(like_num):
            likes += like_num[n]
            n += 1
        for like in likes:
            like.unread = False
    follows = [f for f in user.followers if f.unread is True]

    return render_template('message/like_message.html',
                           title='消息',
                           likes=likes,
                           comments=len(comments),
                           follow=len(follows))

@message.route('/follow')
@login_required
def follow_message():
    user = User.query.filter_by(id=current_user.id).first()
    all_post = user.posts.order_by(Post.timestamp.desc()).all()
    posts = [post for post in all_post if post.draft == False]

    i = [post.comments for post in posts]
    x, comments = 0, []
    if i != []:
        while x < len(i):
            comments += i[x]
            x += 1
        comments = [comment for comment in comments if comment.unread is True]
    like_num = [post.like_num for post in posts]
    n, likes = 0, []
    if like_num != []:
        while n < len(like_num):
            likes += like_num[n]
            n += 1
        likes = [like for like in likes if like.unread is True]
    follows = [f for f in user.followers]
    for f in follows:
        f.unread = False

    return render_template('message/follow_message.html',
                           title='消息',
                           comments=len(comments),
                           likes=len(likes),
                           follows=follows)
# 私信箱
@message.route('/letter')
@login_required
def letter_message():
    user = User.query.filter_by(id=current_user.id).first()
    all_post = user.posts.order_by(Post.timestamp.desc()).all()
    posts = [post for post in all_post if post.draft == False]

    i = [post.comments for post in posts]
    x, comments = 0, []
    if i != []:
        while x < len(i):
            comments += i[x]
            x += 1
        comments = [comment for comment in comments if comment.unread is True]
    like_num = [post.like_num for post in posts]
    n, likes = 0, []
    if like_num != []:
        while n < len(like_num):
            likes += like_num[n]
            n += 1
        likes = [like for like in likes if like.unread is True]
    follows = [f for f in user.followers if f.unread is True]

    page = request.args.get('page', 1, type=int)
    pagination = Conversation.query.filter(
        Conversation.to_user_id == current_user.id,
        ).order_by(Conversation.timestamp.desc()). \
            paginate(page, per_page=current_app.config['MESSAGES_PER_PAGE'],
                     error_out=False)
    conversations = pagination.items
    message_count = Conversation.query.filter(
        Conversation.to_user_id == current_user.id).count()

    return render_template("message/letter_message.html",
                           title='消息',
                           comments=len(comments),
                           likes=len(likes),
                           follows=len(follows),
                           pagination=pagination,
                           conversations=conversations,
                           message_count=message_count)

# 读写私信
@message.route('/write_letter/<int:id>', methods=['GET','POST'])
@login_required
def write_letter(id):
    send_conv = Conversation.query.filter_by(
        to_user_id = id,
        from_user_id = current_user.id
    ).all()
    receive_conv = Conversation.query.filter_by(
        to_user_id = current_user.id,
        from_user_id = id
    ).all()
    if receive_conv:
        for conv in receive_conv:
            conv.unread = False

    form = LetterForm()
    if current_user.operation(Permission.WRITE_ARTICLES) and \
            form.validate_on_submit():
        letter = form.body.data
        conversation = Conversation(from_user_id=current_user.id,
                                    to_user_id=id,
                                    letter=letter,
                                    unread=True)
        db.session.add(conversation)
        flash('发送私信成功。')
        return redirect(url_for('message.write_letter',id=id))
    return render_template('message/conversation.html',
                           title='消息',
                           receive_conv = receive_conv,
                           send_conv = send_conv,
                           all = max(len(receive_conv),len(send_conv)),
                           form=form)

# 删除会话
@message.route('delete_letter/<int:id>')
@login_required
def delete_letter(id):
    conversation = Conversation.query.filter_by(
                                id=id,
                                to_user_id=current_user.id).first_or_404()
    db.session.delete(conversation)
    flash('你已删除此条私信。')

    return redirect(url_for('message.letter_message'))

app/templates/message/comment_message.html
{% extends "base.html" %}

{% block content %}
<div class="row clearfix">
    <div class="col-md-3 column">
        <a href="{{ url_for('message.letter_message') }}" class="list-group-item btn btn-info btn-lg">
          <span class="glyphicon glyphicon-envelope"></span> 私信
        </a><hr>
        <a href="#" class="list-group-item active">
            <span class="glyphicon glyphicon-comment"></span> 评论
        </a>
        <a href="{{ url_for('message.like_message') }}" class="list-group-item">
            <span class="badge">{{ like }}</span><span class="glyphicon glyphicon-thumbs-up"></span> 点赞
        </a>
        <a href="{{ url_for('message.follow_message') }}" class="list-group-item">
            <span class="badge">{{ follow }}</span><span class="glyphicon glyphicon-star"></span> 关注
        </a>

    </div>

    <div class="col-md-9 column">
        最新评论<hr>
        {% if comments == [] %}
        <h4>啊哦，没有新的评论哦。</h4>
        {% else %}
        <ul class="list-group">
            {% for comment in comments %}
            <li class="list-group-item">
                <div>
                    <a href="{{ url_for('user.users', nickname=comment.author.nickname) }}">
                        {{ comment.author.nickname }}
                    </a>评论了文章
                    <a href="{{ url_for('user.post', id=comment.post_id) }}">
                        《{{ comment.post.title }}》
                    </a>
                    <span class="right"><i>{{ moment(comment.timestamp).fromNow() }}</i></span>
                </div>
            </li><br>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/message/conversation.html
{% extends "base.html" %}

{% block content %}
<div class="row clearfix">
    <div class="col-md-3 column">
        {% if receive_conv %}
        <table>
            <tr valign="top">
                <td><img class="images" src="{{receive_conv[0].from_user.gravatar(150)}}"></td>
            </tr>
            <tr>
                <td>
                    <h3>{{receive_conv[0].from_user.nickname}}</h3>
                    {% if receive_conv[0].from_user.about_me %}<p>{{receive_conv[0].from_user.about_me}}</p>{% endif %}
                    {% if receive_conv[0].from_user.last_seen %}<p><i>{{receive_conv[0].from_user.last_seen}}</i></p>{% endif %}
                </td>
            </tr>
        </table>
        {% endif %}
        <hr>
        {% if send_conv %}
        <table>
            <tr valign="top">
                <td><img class="images" src="{{current_user.gravatar(150)}}"></td>
            </tr>
            <tr>
                <td>
                    <h3>{{current_user.nickname}}</h3>
                    {% if current_user.about_me %}<p>{{current_user.about_me}}</p>{% endif %}
                    {% if current_user.last_seen %}<p><i>{{current_user.last_seen}}</i></p>{% endif %}
                </td>
            </tr>
        </table>
        {% endif %}
    </div>
    <div class="col-md-9 column">
        {% if send_conv %}

        <a href="{{ url_for('message.letter_message') }}">返回私信列表</a>
        <span class="letter"><b>与 {{ send_conv[0].to_user.nickname }} 的对话</b></span><hr>

        {% endif %}
        <ul class="list-group">
            {% if receive_conv %}
            {% for r_conv in receive_conv %}
            <li class="list-group-item">
                <table>
                    <tr>
                        <td><img class="images" src="{{r_conv.from_user.gravatar(30)}}"></td>
                        <td>
                            {{ r_conv.letter }}
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><i>{{ moment(r_conv.timestamp).fromNow() }}</i></td>
                    </tr>
                </table>
            </li>
            {% endfor %}
            {% endif %}
            <hr>
            {% if send_conv %}
            {% for s_conv in send_conv %}
            <li class="list-group-item">
                <div>
                <table>
                    <tr>
                        <td><img class="images" src="{{current_user.gravatar(30)}}"></td>
                        <td>
                            {{ s_conv.letter }}
                        </td>

                    </tr>
                    <tr>
                        <td></td>
                        <td><i>{{ moment(s_conv.timestamp).fromNow() }}</i></td>
                    </tr>
                </table>
                </div>
            </li>
            {% endfor %}
            {% endif %}
        </ul>
        <br><hr>
        <form action="" method="post" name="letter">
        {{form.hidden_tag()}}
        {{form.body(class="form-control",rows="3")}}<br>
        {% for error in form.body.errors %}
            <span style="color: red;">[{{error}}]</span>
        {% endfor %}<br>
        <p>
            <input class="btn btn-default right" type="submit" value="发送">
        </p>
        </form>
    </div>

</div>
{% endblock %}

app/templates/message/follow_message.html
{% extends "base.html" %}

{% block content %}
<div class="row clearfix">
    <div class="col-md-3 column">
        <a href="{{ url_for('message.letter_message') }}" class="list-group-item btn btn-info btn-lg">
          <span class="glyphicon glyphicon-envelope"></span> 私信
        </a><hr>
        <a href="{{ url_for('message.comment_message') }}" class="list-group-item">
            <span class="badge">{{ comments }}</span><span class="glyphicon glyphicon-comment"></span> 评论
        </a>
        <a href="{{ url_for('message.like_message') }}" class="list-group-item">
            <span class="badge">{{ likes }}</span><span class="glyphicon glyphicon-thumbs-up"></span> 点赞
        </a>
        <a href="#" class="list-group-item active">
            <span class="glyphicon glyphicon-star"></span> 关注
        </a>
    </div>
    <div class="col-md-9 column">
        最近获得的关注<hr>
        {% if follows == [] %}
        <h4>最近没有人关注过你哦。</h4>
        {% else %}
        <ul class="list-group">
            {% for follow in follows %}
            <li class="list-group-item">
                <div>
                    <a href="{{ url_for('user.users',nickname=follow.followed.nickname) }}">
                        {{ follow.followed.nickname }}
                    </a>关注了你。
                    <span class="right"><i>{{ moment(follow.timestamp).fromNow() }}</i></span>
                </div>
            </li>151404060124@stu.haust.edu.cn
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/message/letter_message.html
{% extends "base.html" %}

{% block content %}
<div class="row clearfix">
    <div class="col-md-3 column">
        <a href="#" class="list-group-item btn btn-info btn-lg active">
          <span class="glyphicon glyphicon-envelope"></span> 私信
        </a><hr>
        <a href="{{ url_for('message.comment_message') }}" class="list-group-item">
            <span class="badge">{{ comments }}</span><span class="glyphicon glyphicon-comment"></span> 评论
        </a>
        <a href="{{ url_for('message.like_message') }}" class="list-group-item">
            <span class="badge">{{ likes }}</span><span class="glyphicon glyphicon-thumbs-up"></span> 点赞
        </a>
        <a href="{{ url_for('message.follow_message') }}" class="list-group-item">
            <span class="badge">{{ follows }}</span><span class="glyphicon glyphicon-star"></span> 关注
        </a>
    </div>
    <div class="col-md-9 column">
        全部私信<hr>
        {% if not conversations %}
        <h4>还没有收到过私信哦。</h4>
        {% else %}
        <ul class="list-group">
            {% for conv in conversations %}
            <li class="list-group-item">
                <a href="{{ url_for('user.users',nickname=conv.from_user.nickname) }}">
                    {{ conv.from_user.nickname }}
                </a>给你发了封私信。
                <a href="{{ url_for('message.write_letter',id=conv.from_user.id) }}"> 回复>>></a>
                <a href="{{ url_for('message.delete_letter',id=conv.id) }}">
                    <span class="label label-danger right">删除</span>
                </a>
            </li><br>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/message/like_message.html
{% extends "base.html" %}

{% block content %}
<div class="row clearfix">
    <div class="col-md-3 column">
        <a href="{{ url_for('message.letter_message') }}" class="list-group-item btn btn-info btn-lg">
          <span class="glyphicon glyphicon-envelope"></span> 私信
        </a><hr>
        <a href="{{ url_for('message.comment_message') }}" class="list-group-item">
            <span class="badge">{{ comments }}</span><span class="glyphicon glyphicon-comment"></span> 评论
        </a>
        <a href="#" class="list-group-item active">
            <span class="glyphicon glyphicon-thumbs-up"></span> 点赞
        </a>
        <a href="{{ url_for('message.follow_message') }}" class="list-group-item">
            <span class="badge">{{ follow }}</span><span class="glyphicon glyphicon-star"></span> 关注
        </a>
    </div>
    <div class="col-md-9 column">
        最近获得的赞<hr>
        {% if likes == [] %}
        <h4>最近没有获得过赞哦。</h4>
        {% else %}
        <ul class="list-group">
            {% for like in likes %}
            <li class="list-group-item">
                <div>
                    <a href="{{ url_for('user.users',nickname=like.user.nickname) }}">
                        {{ like.user.nickname }}
                    </a>赞了你的文章
                    <a href="{{ url_for('user.post',id=like.post.id) }}">
                        《{{ like.post.title }}》
                    </a>。
                    <span class="right"><i>{{ moment(like.timestamp).fromNow() }}</i></span>
                </div>
            </li><br>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}